### PR TITLE
fix(templates/x-basic): expected 1 arguments, but got 2

### PR DESCRIPTION
**Pull request by fzn0x**
fix templates to only includes one argument

### CODE REVIEW

**Comment by yusukebe** [comment]
Hi @fzn0x 

The current template is not wrong. I think loading `app/global.d.ts` is not working well. How about adding the following to `tsconfig.json`?

```json
{
  "include": [
    "**/*.ts",
    "**/*.tsx",
  ],
}
```

**Comment by fzn0x** [comment]
Hi @yusukebe added! Thanks

**Review by yusukebe — APPROVED** [review]
LGTM!

**Comment by yusukebe** [comment]
@fzn0x 

Thanks! Let's go.

**Pull request merged**
